package kioskMenu.MenuOption;

public enum MenuOpt05_Extra {
    WHIPPED_CREAM,
    LOWFAT_MILK,
    SOY_MILK,
    ALMOND_MILK,
    CARAMEL_SYRUP,
    HAZELNUT_SYRUP,
    VANILLA_SYRUP,
    CHOCOLATE_SYRUP,
    SUGAR_FREE_SYRUP,
    ONE_ESPRESSO_SHOT,
    TWO_ESPRESSO_SHOT
}
