package kioskMenu.menuOption;

public enum MenuOpt01_Kind {
    GREEN_TEA,
    PEACH_TEA,
    CHAI_TEA,
    AMERICANO,
    ESPRESSO,
    MOCHA,
    VIENNA,
    CORTADO,
    CAFE_LATTE,
    CAPPUCCINO,
    MACCHIATO,    
    LEMONADE,
    CHOCOLATE_LATTE,
    GREEN_TEA_LATTE,
    ORANGE_JUICE,
    STRAWBERRY_JUICE,
    PINEAPPLE_JUICE,
    WATERMELON_JUICE,
    MANGO_JUICE
    }